def export_html(results, target, filename):
    html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Port Scan Report - {target}</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 1000px; margin: 0 auto; padding: 20px; background-color: #f4f4f9; }}
        h1, h2 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
        .summary {{ background: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 30px; }}
        table {{ width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        th, td {{ padding: 12px 15px; text-align: left; border-bottom: 1px solid #eee; }}
        th {{ background-color: #3498db; color: white; text-transform: uppercase; letter-spacing: 1px; }}
        tr:hover {{ background-color: #f1f7ff; }}
        .status-open {{ color: #27ae60; font-weight: bold; }}
        .footer {{ margin-top: 50px; text-align: center; font-size: 0.9em; color: #7f8c8d; }}
    </style>
</head>
<body>
    <h1>Port Scan Report</h1>
    <div class="summary">
        <h2>Summary</h2>
        <p><strong>Target Host:</strong> {target}</p>
        <p><strong>Scan Date:</strong> {target}</p>
        <p><strong>Open Ports Found:</strong> {len(results)}</p>
    </div>

    <h2>Open Ports</h2>
    <table>
        <thead>
            <tr>
                <th>Port</th>
                <th>Protocol</th>
                <th>State</th>
                <th>Service</th>
                <th>Version</th>
            </tr>
        </thead>
        <tbody>
"""
    for res in results:
        html_content += f"""
            <tr>
                <td>{res['port']}</td>
                <td>{res['protocol']}</td>
                <td class="status-open">{res['state']}</td>
                <td>{res['service']}</td>
                <td>{res['version']}</td>
            </tr>
"""

    html_content += """
        </tbody>
    </table>
    <div class="footer">
        Generated by Python Port Scanner v1.0
    </div>
</body>
</html>
"""
    with open(filename, 'w') as f:
        f.write(html_content)
